const $=(s,e=document)=>e.querySelector(s), $$=(s,e=document)=>[...e.querySelectorAll(s)];
const KEY="ramFitV1", TODAY=()=>new Date().toISOString().slice(0,10);
const mealDefaults={
 breakfast:[{id:"b1",name:"ביצים + יוגורט + סלט",ingredients:[
  {name:"ביצים גדולות",amount:3,unit:"יח׳",p:18.9,k:216,note:"3 ביצים"},
  {name:"יוגורט חלבון",amount:200,unit:"גרם",p:20,k:130,note:"לפי התווית"},
  {name:"סלט / ירקות",amount:200,unit:"גרם",p:3,k:60,note:"ללא רוטב"}]}],
 lunch:[{id:"l1",name:"חזה עוף + אורז",ingredients:[
  {name:"חזה עוף",amount:170,unit:"גרם",p:52.7,k:281,note:"משקל אחרי בישול"},
  {name:"אורז",amount:200,unit:"גרם",p:5.4,k:260,note:"משקל אחרי בישול"},
  {name:"ירקות",amount:200,unit:"גרם",p:3,k:70,note:"בקירוב"},
  {name:"שמן זית",amount:10,unit:"גרם",p:0,k:88,note:"לשקול / למדוד"}]},
 {id:"l2",name:"בולונז + פסטה",ingredients:[
  {name:"בקר טחון רזה",amount:150,unit:"גרם",p:39,k:320,note:"משקל אחרי בישול"},
  {name:"פסטה",amount:220,unit:"גרם",p:12.8,k:345,note:"משקל אחרי בישול"},
  {name:"רוטב עגבניות",amount:150,unit:"גרם",p:2,k:75,note:"לפי המוצר"}]}],
 snack:[{id:"s1",name:"שייק חלבון",ingredients:[{name:"שייק חלבון",amount:1,unit:"מנה",p:24,k:160,note:"לפי המוצר"}]},
 {id:"s2",name:"חטיף חלבון",ingredients:[{name:"חטיף חלבון",amount:1,unit:"יח׳",p:20,k:210,note:"עדכן לפי התווית"}]}],
 dinner:[{id:"d1",name:"ארוחת ערב בסיסית",ingredients:[
  {name:"קוטג׳ / גבינה עשירה בחלבון",amount:250,unit:"גרם",p:30,k:250,note:"לפי המוצר"},
  {name:"לחם",amount:100,unit:"גרם",p:9,k:250,note:"לפי המוצר"},
  {name:"ירקות",amount:200,unit:"גרם",p:3,k:60,note:"ללא רוטב"}]}]
};
const workoutDefaults={
 workout1:{name:"אימון 1",exercises:[["w1e1","Pull-ups","3 סטים"],["w1e2","Shoulder Press","3×8–12"],["w1e3","Triceps Rope Pushdown","3×10–15"],["w1e4","Overhead Triceps Extension","3×10–15"],["w1e5","Cable Curl","3×10–15"],["w1e6","Lateral Raise","3×12–20"]].map(([id,name,target])=>({id,name,target}))},
 workout2:{name:"אימון 2",exercises:[["w2e1","Pull-ups","3 סטים"],["w2e2","Chest Press / Push-ups","3×8–12"],["w2e3","Cable Fly","3×10–15"],["w2e4","Bayesian Curl","3×10–15"],["w2e5","Triceps Extension","3×10–15"],["w2e6","Lateral Raise","3×12–20"]].map(([id,name,target])=>({id,name,target}))},
 workout3:{name:"אימון 3",exercises:[["w3e1","Pull-ups","3 סטים"],["w3e2","Lat Pulldown","3×8–12"],["w3e3","Shoulder Press","3×8–12"],["w3e4","EZ / Dumbbell Curl","3×10–15"],["w3e5","Triceps Rope Pushdown","3×10–15"],["w3e6","Cable Lateral Raise","3×12–20"]].map(([id,name,target])=>({id,name,target}))}
};
function load(){let s;try{s=JSON.parse(localStorage.getItem(KEY)||"null")}catch{}s=s||{settings:{proteinTarget:145,caloriesTarget:2300,weightKg:73,reminders:true,mealTimes:{breakfast:"10:00",lunch:"13:30",snack:"17:00",dinner:"20:00"}},weeklyPlan:{1:"workout1",3:"workout2",5:"workout3"},logs:{}};s.settings=s.settings||{};s.settings.mealTimes=s.settings.mealTimes||{breakfast:"10:00",lunch:"13:30",snack:"17:00",dinner:"20:00"};if(s.settings.reminders===undefined)s.settings.reminders=true;if(!s.meals?.breakfast?.[0]?.ingredients)s.meals=structuredClone(mealDefaults);s.workouts=s.workouts||structuredClone(workoutDefaults);s.weeklyPlan=s.weeklyPlan||{1:"workout1",3:"workout2",5:"workout3"};s.logs=s.logs||{};s.reminderLog=s.reminderLog||{};return s}
let state=load();const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
function log(d=TODAY()){return state.logs[d]||(state.logs[d]={meals:{},workout:{},weight:null})}
const labels={breakfast:"בוקר",lunch:"צהריים",snack:"ביניים",dinner:"ערב"};
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
function baseMeal(type,id){return (state.meals[type]||[]).find(x=>x.id===id)||state.meals[type]?.[0]}
function meal(type,d=TODAY()){let x=log(d).meals[type],b=baseMeal(type,x?.id);return x?.ingredients?x:b}
function mt(m){return (m?.ingredients||[]).reduce((a,i)=>({p:a.p+(+i.p||0),k:a.k+(+i.k||0)}),{p:0,k:0})}
function totals(d=TODAY()){let p=0,k=0;Object.keys(labels).forEach(t=>{if(log(d).meals[t]?.done){let z=mt(meal(t,d));p+=z.p;k+=z.k}});return{p:Math.round(p),k:Math.round(k)}}
const pct=(a,b)=>Math.min(100,Math.round(a/(b||1)*100));
function workout(d=TODAY()){let id=state.weeklyPlan[new Date(d+"T12:00").getDay()];return id?{id,...state.workouts[id]}:null}
function ingredients(m){return(m?.ingredients||[]).map(i=>`<div class="small" style="margin-top:5px"><strong>${esc(i.name)}:</strong> ${i.amount} ${esc(i.unit)} <span class="muted">· ${Math.round(i.p)} ג׳ חלבון · ${Math.round(i.k)} קק״ל · ${esc(i.note)}</span></div>`).join("")}
function renderTodayMeal(t){let m=meal(t),z=mt(m),done=!!log().meals[t]?.done;return`<div class="meal ${done?"done":""}"><div class="row space"><div style="flex:1"><strong>${labels[t]} · ${state.settings.mealTimes[t]}</strong><div>${esc(m?.name||"")}</div>${ingredients(m)}<div style="margin-top:8px"><strong>סה״כ ${Math.round(z.p)} ג׳ חלבון · ${Math.round(z.k)} קק״ל</strong></div></div><input class="check meal-check" data-type="${t}" type="checkbox" ${done?"checked":""}></div></div>`}
function renderToday(){let z=totals(),w=workout();return`<div class="grid two"><section class="card"><div class="muted small">חלבון היום</div><div class="kpi">${z.p}<span class="small"> / ${state.settings.proteinTarget} ג׳</span></div><div class="progress-wrap"><div class="progress-bar" style="width:${pct(z.p,state.settings.proteinTarget)}%"></div></div></section><section class="card"><div class="muted small">קלוריות היום</div><div class="kpi">${z.k}<span class="small"> / ${state.settings.caloriesTarget}</span></div><div class="progress-wrap"><div class="progress-bar" style="width:${pct(z.k,state.settings.caloriesTarget)}%"></div></div></section></div><div class="section-title"><h2>האימון של היום</h2></div><section class="card">${w?`<h3>${esc(w.name)}</h3><button class="btn" data-go="workouts">התחל / המשך אימון</button>`:`<div class="empty">היום יום מנוחה 🛋️</div>`}</section><div class="section-title"><h2>הארוחות של היום</h2><button class="btn secondary" data-go="food">עריכה</button></div><div class="stack">${Object.keys(labels).map(renderTodayMeal).join("")}</div>`}
function editor(t,m){return`<details style="margin-top:10px"><summary><strong>שנה את הכמות שאכלתי</strong></summary>${(m.ingredients||[]).map((i,n)=>`<div class="row space" style="margin-top:10px"><div><strong>${esc(i.name)}</strong><div class="muted small">${esc(i.note)}</div></div><div class="row"><input class="amt" data-type="${t}" data-i="${n}" type="number" step="1" value="${i.amount}" style="width:90px"><span>${esc(i.unit)}</span></div></div>`).join("")}<button class="btn secondary save-amts" data-type="${t}" style="margin-top:10px">שמור כמויות</button></details>`}
function renderFood(){return`<section class="card"><h2>תפריט מדויק</h2><div class="muted">בעוף, אורז, פסטה ובשר: המשקל הוא אחרי בישול, אלא אם מצוין אחרת.</div></section>${Object.keys(labels).map(t=>`<div class="section-title"><h2>${labels[t]} · ${state.settings.mealTimes[t]}</h2></div><div class="stack">${state.meals[t].map((m,n)=>{let cur=log().meals[t],chosen=cur?.id===m.id||(!cur&&n===0),x=chosen?meal(t):m,z=mt(x);return`<div class="meal"><div class="row space"><label style="display:flex;gap:8px;color:inherit;flex:1"><input class="choice" type="radio" name="${t}" data-type="${t}" data-id="${m.id}" ${chosen?"checked":""}><span><strong>${esc(m.name)}</strong>${ingredients(x)}<div style="margin-top:7px"><strong>${Math.round(z.p)} ג׳ · ${Math.round(z.k)} קק״ל</strong></div></span></label>${chosen?`<input class="check meal-check" data-type="${t}" type="checkbox" ${cur?.done?"checked":""}>`:""}</div>${chosen?editor(t,x):""}</div>`}).join("")}</div>`).join("")}`}
function renderWorkouts(){let w=workout();if(!w)return`<section class="card"><h2>אין אימון היום</h2></section>`;let l=log();return`<section class="card"><h2>${w.name}</h2></section><div class="stack" style="margin-top:12px">${w.exercises.map((e,n)=>{let x=l.workout[e.id]||{};return`<div class="exercise"><div class="row space"><strong>${n+1}. ${e.name}</strong><input class="check ex-check" data-ex="${e.id}" type="checkbox" ${x.done?"checked":""}></div><div class="muted small">${e.target}</div><div class="form-grid" style="margin-top:8px"><input class="ex-weight" data-ex="${e.id}" type="number" step=".5" value="${x.weight||""}" placeholder="משקל ק״ג"><input class="ex-reps" data-ex="${e.id}" value="${x.reps||""}" placeholder="חזרות 12,12,10"></div></div>`}).join("")}</div><button id="saveWorkout" class="btn" style="width:100%;margin-top:12px">שמור אימון</button>`}
function renderProgress(){let ds=Object.keys(state.logs).sort().reverse().slice(0,14);return`<section class="card"><h2>התקדמות</h2><div class="row"><input id="weight" type="number" step=".1" value="${log().weight||state.settings.weightKg||""}"><button id="saveWeight" class="btn">שמור משקל</button></div></section><div class="stack" style="margin-top:12px">${ds.map(d=>{let z=totals(d);return`<div class="history-item"><strong>${d}</strong><div class="muted">${z.p} ג׳ חלבון · ${z.k} קק״ל${state.logs[d].weight?" · "+state.logs[d].weight+" ק״ג":""}</div></div>`}).join("")}</div>`}
function renderSettings(){let s=state.settings;return`<section class="card"><h2>יעדים</h2><div class="form-grid"><div><label>חלבון</label><input id="pt" type="number" value="${s.proteinTarget}"></div><div><label>קלוריות</label><input id="kt" type="number" value="${s.caloriesTarget}"></div></div></section><div class="section-title"><h2>שעות ותזכורות</h2></div><section class="card"><label style="color:inherit"><input id="rem" type="checkbox" style="width:auto" ${s.reminders?"checked":""}> הפעל תזכורות</label>${Object.keys(labels).map(t=>`<div class="row space" style="margin-top:10px"><strong>${labels[t]}</strong><input class="meal-time" data-type="${t}" type="time" value="${s.mealTimes[t]}" style="width:130px"></div>`).join("")}<div class="muted small" style="margin-top:12px">כרגע ההתראה פועלת כשהאפליקציה פתוחה. Push כשהאפליקציה סגורה יתווסף בשלב הבא.</div></section><button id="saveSettings" class="btn" style="width:100%;margin-top:12px">שמור הגדרות</button>`}
function render(){let r=location.hash.slice(1)||"today";$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.route===r));$('#todayDate').textContent=new Date().toLocaleDateString('he-IL',{weekday:'long',day:'numeric',month:'long'});$('#view').innerHTML=r==='today'?renderToday():r==='food'?renderFood():r==='workouts'?renderWorkouts():r==='progress'?renderProgress():renderSettings();bind(r)}
function ensureMeal(t){if(!log().meals[t]){let m=state.meals[t][0];log().meals[t]={id:m.id,name:m.name,ingredients:structuredClone(m.ingredients),done:false}}}
function bind(r){$$('[data-go]').forEach(b=>b.onclick=()=>location.hash=b.dataset.go);$$('.meal-check').forEach(c=>c.onchange=()=>{ensureMeal(c.dataset.type);log().meals[c.dataset.type].done=c.checked;save();render()});$$('.choice').forEach(c=>c.onchange=()=>{let m=baseMeal(c.dataset.type,c.dataset.id);log().meals[c.dataset.type]={id:m.id,name:m.name,ingredients:structuredClone(m.ingredients),done:false};save();render()});$$('.save-amts').forEach(b=>b.onclick=()=>{let t=b.dataset.type;ensureMeal(t);let e=log().meals[t],base=baseMeal(t,e.id);$$(`.amt[data-type="${t}"]`).forEach(inp=>{let i=+inp.dataset.i,amt=+inp.value||0,ratio=amt/(base.ingredients[i].amount||1);e.ingredients[i]={...base.ingredients[i],amount:amt,p:base.ingredients[i].p*ratio,k:base.ingredients[i].k*ratio}});save();render()});if(r==='workouts')$('#saveWorkout')?.addEventListener('click',()=>{let w=workout();w.exercises.forEach(e=>{log().workout[e.id]={done:$(`.ex-check[data-ex="${e.id}"]`).checked,weight:$(`.ex-weight[data-ex="${e.id}"]`).value,reps:$(`.ex-reps[data-ex="${e.id}"]`).value}});save();alert('האימון נשמר')});if(r==='progress')$('#saveWeight')?.addEventListener('click',()=>{log().weight=+$('#weight').value;state.settings.weightKg=log().weight;save();render()});if(r==='settings')$('#saveSettings')?.addEventListener('click',async()=>{let s=state.settings;s.proteinTarget=+$('#pt').value;s.caloriesTarget=+$('#kt').value;s.reminders=$('#rem').checked;$$('.meal-time').forEach(i=>s.mealTimes[i.dataset.type]=i.value);save();if(s.reminders&&'Notification'in window&&Notification.permission!=='granted')await Notification.requestPermission();alert('נשמר');render()})}
function reminders(){if(!state.settings.reminders||!('Notification'in window)||Notification.permission!=='granted')return;let n=new Date(),hm=String(n.getHours()).padStart(2,'0')+':'+String(n.getMinutes()).padStart(2,'0');Object.keys(labels).forEach(t=>{if(state.settings.mealTimes[t]!==hm||log().meals[t]?.done)return;let key=TODAY()+t+hm;if(state.reminderLog[key])return;let m=meal(t);new Notification(`Ram Fit · ${labels[t]}`,{body:`השעה ${hm} — הגיע הזמן ל${m?.name||'ארוחה'}.`});state.reminderLog[key]=1;save()})}
$$('.nav-btn').forEach(b=>b.onclick=()=>location.hash=b.dataset.route);window.addEventListener('hashchange',render);$('#notifBtn').onclick=async()=>{'Notification'in window?await Notification.requestPermission():alert('אין תמיכה בהתראות בדפדפן הזה')};if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});setInterval(reminders,20000);render();reminders();