// Ram Fit v18 — robust Google Sheets sync for workout tabs A/B/C.
(function(){
  const SHEET_ID='1SFClMgTbjDfVTv57ukoUZhhcln8QL8MltdWmld53BAk';
  const workoutForTab={A:'workout1',B:'workout2',C:'workout3'};
  const tabCandidates={A:['A','אימון A','Workout A','אימון a','a'],B:['B','אימון B','Workout B','אימון b','b'],C:['C','אימון C','Workout C','אימון c','c']};
  const aliases={
    push_incline_db_press:['incline dumbbell press','incline press'],push_db_shoulder_press:['dumbbell shoulder press','machine shoulder press','shoulder press'],push_cable_lateral_raise:['cable lateral raise','single arm cable lateral raise','single-arm cable lateral raise','lateral raise'],push_cable_fly:['cable fly'],push_rope_pushdown:['rope pushdown','rope triceps pushdown','triceps rope pushdown'],push_overhead_rope_extension:['overhead rope extension','overhead rope triceps extension','overhead triceps extension'],
    pull_pullups:['pull ups','pull-ups','pullups'],pull_chest_supported_row:['chest supported row','chest-supported row'],pull_lat_pulldown:['lat pulldown','lat pull down'],pull_incline_db_curl:['incline dumbbell curl','incline db curl'],pull_cable_curl:['cable curl'],pull_rope_hammer_curl:['rope hammer curl','hammer rope curl'],
    arms_cable_lateral_raise:['cable lateral raise','single arm cable lateral raise','single-arm cable lateral raise','lateral raise'],arms_rope_pushdown:['rope pushdown','rope triceps pushdown','triceps rope pushdown'],arms_reverse_pec_deck:['reverse pec deck','reverse pecdeck','rear delt pec deck'],arms_overhead_rope_extension:['overhead rope extension','overhead rope triceps extension','overhead triceps extension'],arms_ez_bar_curl:['ez bar curl','ez-bar curl','ez curl'],arms_bayesian_curl:['bayesian curl'],arms_farmer_carry:['farmer carry','farmers carry','farmer’s carry',"farmer's carry"]
  };
  function norm(s){return String(s||'').toLowerCase().replace(/[–—-]/g,' ').replace(/[^a-z0-9א-ת.% ]/g,' ').replace(/\s+/g,' ').trim();}
  function parseCsv(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(q&&text[i+1]==='"'){cell+='"';i++;}else q=!q;}else if(ch===','&&!q){row.push(cell);cell='';}else if((ch==='\n'||ch==='\r')&&!q){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell);rows.push(row);row=[];cell='';}else cell+=ch;}if(cell||row.length){row.push(cell);rows.push(row);}return rows;}
  function num(v){const s=String(v??'').trim().replace(',','.');if(!s)return null;const m=s.match(/-?\d+(?:\.\d+)?/);return m?Number(m[0]):null;}
  function findExercise(text,workoutId){const w=state.workouts?.[workoutId],n=norm(text);if(!w||!n)return null;for(const e of w.exercises){const names=[e.name,...(aliases[e.id]||[])].map(norm);if(names.some(x=>x&&(n===x||n.includes(x))))return e;}return null;}
  function detectCols(rows){let cols={weight:null,reps:null,rir:null,set:null};for(const r of rows.slice(0,20)){r.forEach((v,i)=>{const n=norm(v);if(cols.weight===null&&(n.includes('weight')||n.includes('משקל')||n==='kg'||n.includes('ק ג')))cols.weight=i;if(cols.reps===null&&(n==='reps'||n.includes('repetition')||n.includes('חזרות')))cols.reps=i;if(cols.rir===null&&(n==='rir'||n.includes('reserve')||n.includes('רזרבה')))cols.rir=i;if(cols.set===null&&(n==='set'||n==='סט'||n.includes('סט ')))cols.set=i;});}return cols;}
  function parseWorkoutCsv(text,workoutId){const rows=parseCsv(text);if(!rows.length)throw new Error('הלשונית ריקה');const cols=detectCols(rows),result={};let current=null;
    for(const r of rows){const joined=r.filter(Boolean).join(' '),maybe=findExercise(joined,workoutId);if(maybe)current=maybe;if(!current)continue;
      let weight=cols.weight!==null?num(r[cols.weight]):null,reps=cols.reps!==null?num(r[cols.reps]):null,rir=cols.rir!==null?num(r[cols.rir]):null;
      if(weight===null||reps===null){const ns=r.map(num).filter(x=>x!==null);if(ns.length>=2){if(weight===null)weight=ns[ns.length>=3?ns.length-3:0];if(reps===null)reps=ns[ns.length>=2?ns.length-2:1];if(rir===null&&ns.length>=3)rir=ns[ns.length-1];}}
      if(weight!==null&&reps!==null&&reps>0){result[current.id]=result[current.id]||[];const last=result[current.id][result[current.id].length-1];if(!last||last.weight!==weight||last.reps!==reps||last.rir!==rir)result[current.id].push({weight,reps,rir});}
    }
    return result;
  }
  async function fetchCandidate(name){const url=`https://docs.google.com/spreadsheets/d/${SHEET_ID}/gviz/tq?tqx=out:csv&sheet=${encodeURIComponent(name)}&_=${Date.now()}`;const res=await fetch(url,{cache:'no-store'});if(!res.ok)throw new Error(`HTTP ${res.status}`);const text=await res.text();if(/<!doctype html/i.test(text)||/accounts\.google\.com/i.test(text)||/Sign in/i.test(text))throw new Error('PRIVATE');return text;}
  async function fetchTab(tab){let lastErr=null;for(const name of tabCandidates[tab]){try{const text=await fetchCandidate(name);if(text&&text.trim().length>5)return {text,name};}catch(e){lastErr=e;if(e.message==='PRIVATE')throw e;}}throw lastErr||new Error('לא מצאתי לשונית מתאימה');}
  function previewHtml(parsed,workoutId){const w=state.workouts[workoutId];const items=w.exercises.filter(e=>parsed[e.id]?.length).map(e=>`<div class="history-item"><strong>${esc(e.name)}</strong><div class="muted small">${parsed[e.id].map(s=>`${s.weight}×${s.reps}${s.rir!==null?` · RIR ${s.rir}`:''}`).join(' | ')}</div></div>`).join('');return `<div class="stack">${items||'<div class="empty">לא מצאתי סטים תואמים</div>'}</div>`;}
  function saveParsed(tab,parsed,workoutId){const l=log();l.workout=l.workout||{};const w=state.workouts[workoutId];let count=0;w.exercises.forEach(e=>{const sets=parsed[e.id];if(!sets?.length)return;const maxWeight=Math.max(...sets.map(s=>s.weight||0));l.workout[e.id]={done:true,weight:maxWeight,reps:sets.map(s=>s.reps).join(','),rir:sets.map(s=>s.rir??'').join(','),sets,source:'google-sheet',sheet:tab,syncedAt:new Date().toISOString()};count++;});state.scheduleOverrides=state.scheduleOverrides||{};state.scheduleOverrides[TODAY()]=workoutId;state.lastSheetSync={tab,date:TODAY(),at:new Date().toISOString(),count};save();return count;}
  async function syncTab(tab,button){const workoutId=workoutForTab[tab],box=$('#sheetSyncStatus');try{if(button){button.disabled=true;button.textContent='מסנכרן…';}if(box)box.innerHTML='<div class="muted">מתחבר ל-Google Sheets…</div>';const got=await fetchTab(tab),parsed=parseWorkoutCsv(got.text,workoutId),exerciseCount=Object.keys(parsed).length,setCount=Object.values(parsed).reduce((s,a)=>s+a.length,0);if(!exerciseCount)throw new Error(`מצאתי את הלשונית "${got.name}" אבל לא הצלחתי לזהות בה תרגילים/סטים. שלח לי צילום של הלשונית ואכוון את המיפוי.`);if(box)box.innerHTML=`<div class="card" style="margin-top:10px"><strong>✓ חיבור הצליח · ${got.name}</strong><div class="muted small">${exerciseCount} תרגילים · ${setCount} סטים</div>${previewHtml(parsed,workoutId)}<div class="row" style="margin-top:10px"><button class="btn" id="confirmSheetSync">ייבא להיום</button><button class="btn secondary" id="cancelSheetSync">ביטול</button></div></div>`;$('#confirmSheetSync').onclick=()=>{const n=saveParsed(tab,parsed,workoutId);alert(`סונכרנו ${n} תרגילים מאימון ${tab}`);render();};$('#cancelSheetSync').onclick=()=>{if(box)box.innerHTML='';};}
    catch(e){let msg=e.message||'שגיאת סנכרון';if(msg==='PRIVATE')msg='הגיליון לא פתוח לקריאה מהאפליקציה. ב-Google Sheets: Share → General access → Anyone with the link → Viewer. אין צורך בהרשאת עריכה.';if(box)box.innerHTML=`<div class="empty"><strong>ה-Sync לא הצליח</strong><div class="small" style="margin-top:6px">${esc(msg)}</div></div>`;}finally{if(button){button.disabled=false;button.textContent=`Sync ${tab}`;}}}
  const baseRenderWorkoutsSync=renderWorkouts;renderWorkouts=function(){const ls=state.lastSheetSync;return `<section class="card"><div class="row space"><div><h2>סנכרון אימון מ-Google Sheets</h2><div class="muted small">בחר A/B/C. הנתונים מוצגים לבדיקה לפני שהם נכנסים ליומן.</div></div></div><div class="row" style="margin-top:10px;flex-wrap:wrap"><button class="btn sync-sheet" data-tab="A">🔄 Sync A</button><button class="btn sync-sheet" data-tab="B">🔄 Sync B</button><button class="btn sync-sheet" data-tab="C">🔄 Sync C</button></div>${ls?`<div class="muted small" style="margin-top:8px">סנכרון אחרון: ${esc(ls.tab)} · ${esc(ls.date)} · ${ls.count} תרגילים</div>`:''}<div id="sheetSyncStatus"></div></section>`+baseRenderWorkoutsSync();};
  const baseBindSync=bind;bind=function(r){baseBindSync(r);if(r!=='workouts')return;$$('.sync-sheet').forEach(b=>b.addEventListener('click',()=>syncTab(b.dataset.tab,b)));};
})();